# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Woven composites material assignment', kernelModule='mat_script_new', kernelFunction='assign_woven_composite_mat', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Matrix')
RsgComboBox(name='ComboBox_2', p='TabItem_1', text='Part', keyword='partName', default='', comboType='MDB', repository='parts', rootText='Model', rootKeyword='modelName', layout='HORIZONTAL')
RsgSeparator(p='TabItem_1')
RsgVerticalAligner(name='VAligner_1', p='TabItem_1', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText="Young\\'s modulus", keyword='matrix_E', default='0.0')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText="Poisson\\'s ratio", keyword='matrix_poissons', default='0.0')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='Coeff. thermal expansion', keyword='matrix_alpha', default='0.0')
RsgTextField(p='VAligner_1', fieldType='Integer', ncols=12, labelText='Number of Kelvin branches', keyword='matrix_num_KB', default='1')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='Specific heat capacity per volume', keyword='matrix_cpt', default='0')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='Initial temperature', keyword='matrix_tinit', default='0')
RsgSeparator(p='TabItem_1')
RsgGroupBox(name='GroupBox_1', p='TabItem_1', text='Kelvin branch parameters', layout='0')
RsgTable(p='GroupBox_1', numRows=4, columnData=[('Elastic moduli', 'Float', 100), ('Viscous moduli', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='matrix_viscoelastic', popupFlags='AFXTable.POPUP_INSERT_ROW')
RsgSeparator(p='TabItem_1')
RsgGroupBox(name='GroupBox_3', p='TabItem_1', text='Viscoplasticity/damage parameters', layout='0')
RsgTable(p='GroupBox_3', numRows=1, columnData=[('R0', 'Float', 50), ('K', 'Float', 50), ('n', 'Float', 50), ('H', 'Float', 50), ('m', 'Float', 50), ('S', 'Float', 50), ('Beta', 'Float', 50)], showRowNumbers=False, showGrids=True, keyword='matrix_viscoplstic_damage', popupFlags='')
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Yarn')
RsgVerticalAligner(name='VAligner_2', p='TabItem_2', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Pure transverse tension threshold', keyword='yarn_R22', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Pure in-plane shear threshold', keyword='yarn_R12', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Weibull length parameter', keyword='yarn_S', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Weibul l exponent parameter', keyword='yarn_beta', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Micro-cracks saturation', keyword='yarn_gamma_inf', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Anelasticity parameter-transverse tension', keyword='yarn_a22', default='0')
RsgTextField(p='VAligner_2', fieldType='Float', ncols=12, labelText='Anelasticity parameter - in plane shear', keyword='yarn_a12', default='0')
RsgSeparator(p='TabItem_2')
RsgGroupBox(name='GroupBox_5', p='TabItem_2', text='Eshelby tensor', layout='0')
RsgTextField(p='GroupBox_5', fieldType='Integer', ncols=12, labelText='Number of gauss points along direction 1', keyword='yarn_m_gauss', default='2')
RsgTextField(p='GroupBox_5', fieldType='Integer', ncols=12, labelText='Number of gauss points along direction 2', keyword='yarn_n_gauss', default='2')
RsgLabel(p='GroupBox_5', text='Ellipsoidal void inclusion dimension', useBoldFont=False)
RsgTable(p='GroupBox_5', numRows=1, columnData=[('a1', 'Float', 100), ('a2', 'Float', 100), ('a3', 'Float', 100)], showRowNumbers=False, showGrids=True, keyword='yarn_inclusion_dimension', popupFlags='')
RsgSeparator(p='TabItem_2')
RsgGroupBox(name='GroupBox_4', p='TabItem_2', text='Initial stiffness(transverse isotropy)', layout='0')
RsgTable(p='GroupBox_4', numRows=1, columnData=[('C1111', 'Float', 50), ('C1122', 'Float', 50), ('C2222', 'Float', 50), ('C2233', 'Float', 50), ('C1212', 'Float', 50)], showRowNumbers=True, showGrids=True, keyword='yarn_stiffness', popupFlags='')
dialogBox.show()